config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'

  get 'pets/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :dashboard
  resources :pets
  resources :appointments
  
  root 'home#index'
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.veterinarian?
      can [:create, :read], Appointment
      can :read, Pet
    elsif user.receptionist?
      can [:create, :read], Appointment
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :pet
  
  validates :date_of_visit, :presence => true
  validate :not_in_the_past
  validates :pet_id, :presence => true
  validates :user_id, :presence => true
  validates :reason_for_visit, :presence => true
  
  def not_in_the_past
    if date_of_visit < Date.today
      errors.add(:date, "cannot schedule a date in the past.")
    end
  end
  
  def appointment_reminder
    if requires_a_reminder?
      "Y"
    else
      "N"
    end
  end
  
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_many :appointments
  
  PET_TYPES = %w(Dog Cat Bird)
  
  validates :name_of_pet, :presence => true, :length => { maximum: 35 }
  validates_inclusion_of :type_of_pet, in: PET_TYPES
  validates :breed, :presence => true, :length => { maximum: 35 }
  validates :age, :presence => true
  validates :weight, :presence => true
  validates :date_last_visited, :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets
  has_many :appointments
  
  enum role: [:user, :admin, :veterinarian, :receptionist, :customer]
  after_initialize :set_default_role, :if => :new_record?
  
  def set_default_role
    self.role ||= :user
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  ZIP_REGEX = /\d{5}/
  validates :name,              :presence     => true,
                                :length       => { maximum: 35 }
  validates :zip,               :length       => { maximum: 5 },
                                :format       => { with: ZIP_REGEX, allow_blank: true }
  validates :years_in_practice, :numericality => { 
                                                   only_integer: true, 
                                                   greater_than: 0, 
                                                   less_than: 101,
                                                   allow_blank: true
                                                  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @appointments = Appointment.all
  end
  
  def new
    @appointment = Appointment.new
    @pets = Pet.all
  end
  
  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash[:success] = "Appointment scheduled!"
      redirect_to appointments_path
    else
      flash[:danger] = "An error occurred."
      render :new
    end
  end
  
  private
  
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :pet_id, :user_id, 
                                          :requires_a_reminder, 
                                          :reason_for_visit, :vet_id)
    end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @appointments = Appointment.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if user_signed_in?
      redirect_to controller: 'dashboard', action: 'index'
    end
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @pets = Pet.all
  end
  
  def new
    @pet = Pet.new
  end
  
  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      flash[:success] = "Pet registered!"
      redirect_to pets_path
    else
      flash[:danger] = "Something went wrong."
      render 'new'
    end
  end
  
  private
  
    def pet_params
      params.require(:pet).permit(:name_of_pet, :user_id, :type_of_pet, :breed, 
                                  :age, :weight, :date_last_visited)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/appointments/_appointments_list.html.erb
<h2>Viewing Appointments</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Requires A reminder?</th>
      <th>Veterinarian</th>
      <th>Reason for Visit</th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= Pet.find(appointment.pet_id).name_of_pet %></td>
        <td><%= User.find(appointment.user_id).name %></td>
        <td><%= appointment.appointment_reminder %></td>
        <td><%= User.find(appointment.vet_id).name %></td>
        <td><%= appointment.reason_for_visit %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/_form.html.erb
<table summary="New appointment form fields">
  <tr>
    <th><%= f.label(:date_of_visit, "Date") %></th>
    <td><%= f.date_select(:date_of_visit, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:pet_id, "Name") %></th>
    <td><%= f.collection_select(:pet_id, Pet.all, :id, :name_of_pet, { prompt: "Select Pet" }, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:user_id, "Owner") %></th>
    <td><%= f.collection_select(:user_id, User.where(role: 4), :id, :name, { prompt: "Select Owner" }, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:requires_a_reminder, "Requires a reminder?") %></th>
    <td><%= f.check_box(:requires_a_reminder) %></td>
  </tr>
  <tr>
    <th><%= f.label(:reason_for_visit, "Reason for visit") %></th>
    <td><%= f.text_field(:reason_for_visit, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:vet_id, "Veterinarian") %></th>
    <td><%= f.collection_select(:vet_id, User.where(role: 2), :id, :name, { prompt: "Select Veterinarian" }, class: "form-control") %></td>
  </tr>
</table>

app/views/appointments/index.html.erb
<%= render 'appointments_list' %>

<%= link_to "New Appointment", new_appointment_path, class: "btn btn-primary" %>

<hr />
<%= link_to "Home", root_path %>

app/views/appointments/new.html.erb
<h2>Schedule an Appointment</h2>

<%= form_for(:appointment, :url => {:action => 'create'}) do |f| %>
  
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  
  <%= f.submit("Schedule Appointment", class: "btn btn-primary") %>
  
<% end %>

<hr />
<%= link_to "Home", root_path %>

app/views/dashboard/_admin_view.html.erb
<%= link_to "Site Administration", rails_admin_path %><br />
<%= link_to "View Appointments", appointments_path %><br />
<%= link_to "View Pets", pets_path %>

app/views/dashboard/_customer_view.html.erb
<%= render 'appointments/appointments_list' %>

app/views/dashboard/_receptionist_view.html.erb
<%= link_to "View Appointments", appointments_path %>

app/views/dashboard/_veterinarian_view.html.erb
<%= link_to "View Appointments", appointments_path %><br />
<%= link_to "View Pets Index", pets_path %><br />

app/views/dashboard/index.html.erb
<h1><%= "#{current_user.role.capitalize} Dashboard" %></h1>
<hr />

<% if current_user.admin? %>
  <%= render 'admin_view' %>
<% elsif current_user.veterinarian? %>
  <%= render 'veterinarian_view' %>
<% elsif current_user.receptionist? %>
  <%= render 'receptionist_view' %>
<% else %>
  <%= render 'customer_view' %>
<% end %>

<hr />
<%= link_to "Home", root_path %>

app/views/home/index.html.erb
<h1>Veterinary Practice App</h1><hr />

<h2>Welcome!</h2>
<p>This is a basic Rails app for managing a small veterinary practice.</p>
<p>There are four different user types, and each has a preconfigured login:</p>
<div>
  <ol>
    <li><em>admin</em>@example.com / password</li>
    <li><em>veterinarian</em>@example.com / password</li>
    <li><em>receptionist</em>@example.com / password</li>
    <li><em>customer</em>@example.com / password</li>
  </ol>
</div>
<p>Try out each account!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinary Practice App</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <div class="container">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign up' , new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
    
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pets/_form.html.erb
<table summary="New pet form fields">
  <tr>
    <th><%= f.label(:name_of_pet, "Name") %></th>
    <td><%= f.text_field(:name_of_pet, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:user_id, "Owner") %></th>
    <td><%= f.text_field(:user_id, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:type_of_pet, "Type") %></th>
    <td><%= f.select(:type_of_pet, ['Dog', 'Cat', 'Bird'], class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:breed, "Breed") %></th>
    <td><%= f.text_field(:breed, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:age, "Age in years") %></th>
    <td><%= f.number_field(:name_of_pet, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:weight, "Weight in lbs") %></th>
    <td><%= f.number_field(:name_of_pet, class: "form-control") %></td>
  </tr>
  <tr>
    <th><%= f.label(:date_last_visited, "Date of Last Visit") %></th>
    <td><%= f.date_select(:name_of_pet, class: "form-control") %></td>
  </tr>
</table>

app/views/pets/index.html.erb
<h2>Viewing All Pets</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name of Pet</th>
      <th>Type</th>
      <th>Breed</th>
      <th>Age in Years</th>
      <th>Weight in lbs</th>
      <th>Owner</th>
      <th>Date of Last Visit</th>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name_of_pet %></td>
        <td><%= pet.type_of_pet %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= User.find(pet.user_id).name %></td>
        <td><%= pet.date_last_visited %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />
<%= link_to "Home", root_path %>

app/views/pets/new.html.erb
<h2>Record a New Pet</h2>

<%= form_for(:pet, :url => {:action => 'create'}) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>
  
  <%= f.submit("Add Pet", class: "btn btn-primary") %>
  
<% end %>

<hr />
<%= link_to "Home", root_path %>